using System.Diagnostics;

namespace IguanaSV.Api.Tests.Schema;

/// <summary>
/// Shared preflight probes and the `dotnet ef` CLI runner used by the schema
/// integration tests. All EF commands target an EPHEMERAL Testcontainers
/// PostgreSQL instance via an explicit --connection string; the developer or
/// CI host database is never touched.
/// </summary>
internal static class EfCli
{
    /// <summary>Migration ids generated by this repository, in apply order.</summary>
    public const string LastPreW2Migration = "20260908201510_AddRolesYPerfilAnfitrion";
    public const string M1AbsorbDrift = "20260918172612_AbsorbPendingSchemaDrift";

    public static string RepoRoot => Guard.GuardScan.RepoRoot;

    public static async Task<bool> DockerAvailableAsync()
    {
        var (exit, _, _) = await RunAsync("docker", "version", RepoRoot, TimeSpan.FromSeconds(30));
        return exit == 0;
    }

    public static async Task<bool> EfToolAvailableAsync()
    {
        var (exit, stdout, _) = await RunAsync(
            "dotnet", "tool list --global", Environment.CurrentDirectory, TimeSpan.FromSeconds(60));
        return exit == 0 && stdout.Contains("dotnet-ef", StringComparison.OrdinalIgnoreCase);
    }

    /// <summary>
    /// Runs `dotnet ef database update [target] --connection <conn>` against the
    /// API project. Throws with stderr on failure.
    /// </summary>
    public static async Task DatabaseUpdateAsync(string? targetMigration, string connection)
    {
        var args = "ef database update"
                   + (targetMigration is null ? string.Empty : $" {targetMigration}")
                   + " --project Backend/IguanaSV.Api --startup-project Backend/IguanaSV.Api"
                   + $" --connection \"{connection}\"";

        var (exit, stdout, stderr) = await RunAsync("dotnet", args, RepoRoot, TimeSpan.FromMinutes(5));
        if (exit != 0)
        {
            throw new InvalidOperationException(
                $"dotnet ef database update {(targetMigration ?? "<latest>")} failed (exit {exit}).\n" +
                $"stdout:\n{stdout}\nstderr:\n{stderr}");
        }
    }

    private static async Task<(int Exit, string StdOut, string StdErr)> RunAsync(
        string fileName, string arguments, string workingDirectory, TimeSpan timeout)
    {
        var psi = new ProcessStartInfo(fileName, arguments)
        {
            WorkingDirectory = workingDirectory,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false,
            CreateNoWindow = true,
        };

        using var process = Process.Start(psi)
            ?? throw new InvalidOperationException($"Failed to start '{fileName} {arguments}'.");

        var stdoutTask = process.StandardOutput.ReadToEndAsync();
        var stderrTask = process.StandardError.ReadToEndAsync();

        if (!process.WaitForExit((int)timeout.TotalMilliseconds))
        {
            process.Kill(entireProcessTree: true);
            throw new TimeoutException($"'{fileName} {arguments}' exceeded {timeout}.");
        }

        return (process.ExitCode, await stdoutTask, await stderrTask);
    }
}
